/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    BackButton: typeof import('./src/components/buttons/BackButton.vue')['default']
    CloseButton: typeof import('./src/components/buttons/CloseButton.vue')['default']
    FFFoundDialog: typeof import('./src/components/dialogs/FFFoundDialog.vue')['default']
    FFFoundDialogProvider: typeof import('./src/components/dialogs/FFFoundDialogProvider.vue')['default']
    FlyingBubble: typeof import('./src/components/FlyingBubble.vue')['default']
    HelpButton: typeof import('./src/components/buttons/HelpButton.vue')['default']
    HelpDialog: typeof import('./src/components/dialogs/HelpDialog.vue')['default']
    HomeButton: typeof import('./src/components/buttons/HomeButton.vue')['default']
    LogoHeader: typeof import('./src/components/LogoHeader.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NFlex: typeof import('naive-ui')['NFlex']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NProgress: typeof import('naive-ui')['NProgress']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSelect: typeof import('naive-ui')['NSelect']
    NSlider: typeof import('naive-ui')['NSlider']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NText: typeof import('naive-ui')['NText']
    NTooltip: typeof import('naive-ui')['NTooltip']
    PreviewNotAvailable: typeof import('./src/components/main/PreviewNotAvailable.vue')['default']
    Processing: typeof import('./src/components/main/Processing.vue')['default']
    RescanFolderButton: typeof import('./src/components/main/RescanFolderButton.vue')['default']
    ResetSettingsButton: typeof import('./src/components/buttons/ResetSettingsButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsButton: typeof import('./src/components/buttons/SettingsButton.vue')['default']
    Setup: typeof import('./src/components/main/Setup.vue')['default']
    TitledHeader: typeof import('./src/components/TitledHeader.vue')['default']
    VideoItem: typeof import('./src/components/main/VideoItem.vue')['default']
  }
}
